# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: ci

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test-race:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Faster
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: *
      - uses: actions/checkout@v2
      - name: Run Tests
        run: go test -race -timeout=30m -count=1 -json -v "github.com/couchbase/go-blip" | tee test.json | jq -s -jr 'sort_by(.Package,.Time) | .[].Output | select (. != null )'
        shell: bash
      - name: Annotate Failures
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json
